# Базовый образ Node.js
FROM node:18-alpine

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm ci

# Копируем код для dev
COPY . .

# Порт для dev
EXPOSE 3000

# Запуск dev-сервера
CMD ["npm", "run", "dev"]
